# This workflow runs for every pull request to lint and test the proposed changes.

name: Check

on:
    # Push to main will deploy a beta version
    push:
        branches: [main, renovate/**]
    pull_request:
        branches: [main]
    # A release via GitHub releases will deploy a latest version
    release:
        types: [published]

jobs:
    build_and_test:
        name: Build & Test
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]
                node-version: [20, 22]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Enable corepack
              run: |
                  corepack enable
                  corepack prepare yarn@stable --activate

            - name: Activate cache for Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  cache: yarn

            - name: Install Dependencies
              run: yarn

            - name: Run Tests
              env:
                  TEST_USER_TOKEN: ${{ secrets.APIFY_TEST_USER_API_TOKEN }}
                  ACTOR_CLI_DISABLE_TELEMETRY: 1
              run: yarn test

    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Enable corepack
              run: |
                  corepack enable
                  corepack prepare yarn@stable --activate

            - name: Activate cache for Node.js 20
              uses: actions/setup-node@v4
              with:
                  cache: yarn

            - name: Install Dependencies
              run: yarn

            - name: Run lint checks
              run: yarn lint

            - name: Run format checks
              run: yarn format
